"""Add concise English display metadata to the author registry."""
import csv
from pathlib import Path

path = Path("data/source_registry/all_people.csv")

profiles = {
    "Jane Austen": ("English novelist; Pride and Prejudice, Emma; precise social comedy", "witty, observant, elegant, ironic"),
    "Charles Dickens": ("English novelist and social critic; Oliver Twist, Great Expectations; Victorian social realism", "expansive, theatrical, compassionate, satirical"),
    "George Eliot": ("English novelist; Middlemarch, Silas Marner; psychological realism", "analytical, humane, morally searching, panoramic"),
    "Thomas Hardy": ("English novelist and poet; Tess of the d'Urbervilles, Jude the Obscure; tragic naturalism", "melancholic, fatalistic, pastoral, stark"),
    "Mark Twain": ("American novelist and humorist; Adventures of Huckleberry Finn; vernacular satire", "wry, colloquial, irreverent, humane"),
    "Edgar Allan Poe": ("American poet, short-story writer, and critic; pioneering detective and gothic fiction", "macabre, hypnotic, ornate, claustrophobic"),
    "Virginia Woolf": ("English novelist and essayist; Mrs Dalloway, To the Lighthouse; modernist interiority", "lyrical, fluid, introspective, impressionistic"),
    "James Joyce": ("Irish novelist and modernist; Ulysses, Dubliners; radical stream-of-consciousness", "experimental, polyphonic, allusive, labyrinthine"),
    "George Orwell": ("English novelist and essayist; Nineteen Eighty-Four, Animal Farm; political language critic", "lucid, austere, polemical, prophetic"),
    "Ernest Hemingway": ("American novelist and journalist; The Sun Also Rises, The Old Man and the Sea; Nobel laureate", "spare, stoic, muscular, understated"),
    "William Faulkner": ("American novelist; The Sound and the Fury, As I Lay Dying; Nobel laureate of Southern modernism", "ornate, recursive, torrential, haunted"),
    "James Baldwin": ("American novelist and essayist; Giovanni's Room, The Fire Next Time; civil-rights intellectual", "incisive, eloquent, intimate, prophetic"),
    "Toni Morrison": ("American novelist and editor; Beloved, Song of Solomon; Nobel laureate", "incantatory, mythic, polyphonic, devastating"),
    "Marcel Proust": ("French novelist; In Search of Lost Time; architect of memory-driven modernism", "sensuous, recursive, analytical, opulent"),
    "Gustave Flaubert": ("French novelist; Madame Bovary; architect of modern realist style", "exact, impersonal, ironic, sculpted"),
    "Albert Camus": ("French-Algerian novelist and philosopher; The Stranger, The Plague; Nobel laureate", "lucid, existential, spare, sunlit"),
    "Franz Kafka": ("German-language novelist and short-story writer; The Trial, The Metamorphosis; modernist emblem", "absurd, claustrophobic, bureaucratic, dreamlike"),
    "Johann Wolfgang von Goethe": ("German writer, thinker, and statesman; Faust, The Sorrows of Young Werther; Weimar polymath", "lyrical, philosophical, expansive, classical"),
    "Jorge Luis Borges": ("Argentine writer and poet; Ficciones, Labyrinths; metaphysical fabulist", "erudite, labyrinthine, crystalline, paradoxical"),
    "Gabriel Garcia Marquez": ("Colombian novelist and journalist; One Hundred Years of Solitude; Nobel laureate", "baroque, magical, cyclical, folkloric"),
    "Lu Xun": ("Chinese writer and essayist; Diary of a Madman, The True Story of Ah Q; founder of modern Chinese literature", "biting, allegorical, austere, subversive"),
    "Natsume Soseki": ("Japanese novelist and scholar; I Am a Cat, Kokoro; architect of modern Japanese fiction", "wry, restrained, psychological, quietly ironic"),
    "Fyodor Dostoevsky": ("Russian novelist; Crime and Punishment, The Brothers Karamazov; psychological realist", "fevered, polyphonic, penitential, abyssal"),
    "Leo Tolstoy": ("Russian novelist and moral thinker; War and Peace, Anna Karenina; global realist canon", "epic, lucid, humane, panoramic"),
    "Anton Chekhov": ("Russian playwright and short-story writer; The Cherry Orchard, Uncle Vanya; master of modern realism", "subtle, quiet, bittersweet, observant"),
    "Abraham Lincoln": ("16th U.S. president; led the Union through the Civil War and issued the Emancipation Proclamation", "plainspoken, solemn, aphoristic, moral"),
    "Theodore Roosevelt": ("26th U.S. president, reformer, and conservationist; Nobel Peace Prize", "vigorous, martial, expansive, reformist"),
    "Franklin D. Roosevelt": ("32nd U.S. president; New Deal architect and wartime leader", "reassuring, pragmatic, intimate, commanding"),
    "John F. Kennedy": ("35th U.S. president; Cold War leader and advocate of public service", "crisp, aspirational, polished, rhythmic"),
    "Winston Churchill": ("British statesman and wartime prime minister; Nobel Prize in Literature", "oratorical, defiant, grand, indomitable"),
    "Martin Luther King Jr.": ("American minister and civil-rights leader; Nobel Peace Prize", "prophetic, cadenced, compassionate, galvanizing"),
    "Nelson Mandela": ("South African anti-apartheid leader and president; Nobel Peace Prize", "measured, conciliatory, dignified, resolute"),
    "Margaret Thatcher": ("British prime minister and Conservative reformer; first woman to hold the office", "assertive, doctrinal, disciplined, combative"),
    "Barack Obama": ("44th U.S. president, constitutional lawyer, and author; Nobel Peace Prize", "measured, reflective, inclusive, soaring"),
    "Donald Trump": ("American businessman and political figure; 45th and 47th U.S. president", "blunt, repetitive, combative, performative"),
    "Joe Biden": ("46th U.S. president and longtime senator; infrastructure and industrial-policy agenda", "empathetic, colloquial, resolute, reassuring"),
    "Angela Merkel": ("German chancellor; central European leader during the euro and migration crises", "deliberate, technical, pragmatic, understated"),
    "Emmanuel Macron": ("French president and former economy minister; pro-European reformer", "rhetorical, technocratic, ambitious, cerebral"),
    "Pope Francis": ("Argentine pope and Catholic reform voice; Laudato si' and social-justice advocacy", "pastoral, humble, compassionate, direct"),
    "Greta Thunberg": ("Swedish climate activist; global youth climate-movement organizer", "urgent, stark, uncompromising, moral"),
    "Malala Yousafzai": ("Pakistani education activist; Nobel Peace Prize and girls' education advocate", "clear, courageous, hopeful, resolute"),
    "Henry James": ("American-British novelist; The Portrait of a Lady, The Ambassadors; master of psychological point of view", "subtle, ceremonious, psychologically coiled, finely shaded"),
    "Edith Wharton": ("American novelist and designer; The Age of Innocence, The House of Mirth; first woman to win the Pulitzer Prize for Fiction", "coolly observant, socially surgical, polished, elegiac"),
    "Herman Melville": ("American novelist and poet; Moby-Dick, Bartleby; visionary chronicler of obsession and the sea", "biblical, oceanic, digressive, metaphysically charged"),
    "Nathaniel Hawthorne": ("American novelist and short-story writer; The Scarlet Letter, Twice-Told Tales; explorer of Puritan guilt", "allegorical, shadowed, morally ambivalent, antique"),
    "Washington Irving": ("American essayist and short-story pioneer; Rip Van Winkle, The Legend of Sleepy Hollow", "urbane, folkloric, gently comic, autumnal"),
    "Louisa May Alcott": ("American novelist and abolitionist; Little Women, Work; chronicler of women's independence and family life", "warmhearted, brisk, domestic, quietly rebellious"),
    "Kate Chopin": ("American novelist and short-story writer; The Awakening, Bayou Folk; early voice of female autonomy", "sensuous, compressed, unsentimental, awakening"),
    "Willa Cather": ("American novelist; My Ántonia, O Pioneers!; chronicler of immigrant life on the Great Plains", "spacious, luminous, earthbound, elegiac"),
    "Jack London": ("American novelist and journalist; The Call of the Wild, Martin Eden; adventure naturalist", "propulsive, elemental, hard-bitten, survivalist"),
    "Stephen Crane": ("American novelist, poet, and war correspondent; The Red Badge of Courage, Maggie; early American naturalist", "impressionistic, ironic, lean, battle-lit"),
    "Charlotte Bronte": ("English novelist and poet; Jane Eyre, Villette; Gothic innovator of female interiority", "ardent, intimate, gothic, fiercely self-possessed"),
    "Emily Bronte": ("English novelist and poet; Wuthering Heights; singular visionary of passion and the moors", "tempestuous, elemental, haunted, savage-romantic"),
    "Anne Bronte": ("English novelist and poet; The Tenant of Wildfell Hall, Agnes Grey; realist critic of marriage and dependency", "plainspoken, morally exacting, sober, quietly radical"),
    "Mary Wollstonecraft Shelley": ("English novelist; Frankenstein, The Last Man; foundational figure in science fiction", "gothic, philosophical, desolate, Promethean"),
    "Robert Louis Stevenson": ("Scottish novelist and essayist; Treasure Island, Strange Case of Dr Jekyll and Mr Hyde", "adventurous, lucid, shadow-doubled, fleet"),
    "Joseph Conrad": ("Polish-British novelist and mariner; Heart of Darkness, Lord Jim; modernist analyst of empire", "brooding, maritime, oblique, morally fogbound"),
    "H. G. Wells": ("English novelist and social thinker; The Time Machine, The War of the Worlds; pioneer of scientific romance", "speculative, brisk, satirical, future-facing"),
    "Frances Hodgson Burnett": ("British-American novelist and playwright; The Secret Garden, A Little Princess; classic children's storyteller", "tender, restorative, garden-bright, sentimental"),
    "L. M. Montgomery": ("Canadian novelist; Anne of Green Gables, Emily of New Moon; chronicler of imagination and island community", "buoyant, picturesque, wistful, spirited"),
    "Elizabeth Cleghorn Gaskell": ("English novelist and biographer; North and South, Cranford; interpreter of industrial conflict", "sympathetic, socially alert, domestic, quietly panoramic"),
    "Anthony Trollope": ("English novelist and civil servant; the Barsetshire and Palliser series; chronicler of institutions", "conversational, patient, institutional, dryly amused"),
    "Wilkie Collins": ("English novelist and playwright; The Woman in White, The Moonstone; pioneer of sensation and detective fiction", "suspenseful, intricate, conspiratorial, page-turning"),
    "Arthur Conan Doyle": ("Scottish writer and physician; creator of Sherlock Holmes; architect of modern detective fiction", "deductive, brisk, atmospheric, clue-driven"),
    "George MacDonald": ("Scottish author and minister; Phantastes, The Princess and the Goblin; formative fantasy writer", "mystical, fairy-lit, allegorical, childlike-wise"),
    "D. H. Lawrence": ("English novelist and poet; Sons and Lovers, Women in Love; explorer of desire and industrial modernity", "sensual, volcanic, instinctive, polemically alive"),
    "E. M. Forster": ("English novelist and essayist; A Passage to India, Howards End; critic of class and imperial distance", "lucid, humane, ironic, connection-seeking"),
    "Katherine Mansfield": ("New Zealand modernist short-story writer; The Garden Party, Bliss; innovator of lyrical compression", "delicate, elliptical, fleeting, emotionally prismatic"),
    "W. E. B. Du Bois": ("American sociologist, historian, and civil-rights leader; The Souls of Black Folk; co-founder of the NAACP", "prophetic, scholarly, double-voiced, emancipatory"),
    "Zora Neale Hurston": ("American novelist, folklorist, and anthropologist; Their Eyes Were Watching God, Mules and Men", "vernacular-rich, exuberant, folkloric, self-possessed"),
    "F. Scott Fitzgerald": ("American novelist; The Great Gatsby, Tender Is the Night; chronicler of Jazz Age glamour and loss", "glittering, wistful, romantic, disillusioned"),
    "John Steinbeck": ("American novelist; The Grapes of Wrath, East of Eden; Nobel laureate and chronicler of working people", "earthy, compassionate, biblical, socially rooted"),
    "Ralph Ellison": ("American novelist and critic; Invisible Man, Shadow and Act; analyst of race, identity, and American democracy", "jazz-inflected, layered, satirical, intellectually electric"),
    "Joan Didion": ("American essayist and novelist; Slouching Towards Bethlehem, The White Album; anatomist of American fracture", "cool, crystalline, ominous, reportorial"),
    "Ursula K. Le Guin": ("American novelist and essayist; Earthsea, The Left Hand of Darkness; major speculative anthropologist", "lucid, anthropological, mythic, quietly anarchic"),
    "Kurt Vonnegut": ("American novelist; Slaughterhouse-Five, Cat's Cradle; satirist of war and technological folly", "deadpan, humane, absurdist, deceptively simple"),
    "Flannery O'Connor": ("American short-story writer and novelist; A Good Man Is Hard to Find, Wise Blood; Southern Gothic moralist", "grotesque, mordant, grace-struck, darkly comic"),
    "Emile Zola": ("French novelist and journalist; Germinal, the Rougon-Macquart cycle; founder of literary naturalism", "forensic, crowded, materialist, socially volcanic"),
    "Jean-Paul Sartre": ("French philosopher, novelist, and playwright; Nausea, No Exit; central theorist of existentialism", "dialectical, existential, severe, freedom-obsessed"),
    "Simone de Beauvoir": ("French philosopher, novelist, and memoirist; The Second Sex; foundational feminist existentialist", "incisive, embodied, analytical, emancipatory"),
    "Colette": ("French novelist and performer; Chéri, Gigi; sensual chronicler of gender and appetite", "tactile, feline, intimate, sensuously exact"),
    "Friedrich Nietzsche": ("German philosopher and philologist; Thus Spoke Zarathustra, Beyond Good and Evil; radical critic of morality", "aphoristic, incendiary, prophetic, hammer-struck"),
    "Thomas Mann": ("German novelist and essayist; The Magic Mountain, Buddenbrooks; Nobel laureate of bourgeois decline", "ironic, symphonic, cerebral, decadently precise"),
    "Bertolt Brecht": ("German playwright and poet; The Threepenny Opera, Mother Courage; creator of epic theatre", "didactic, estranging, sardonic, streetwise"),
    "Hannah Arendt": ("German-American political theorist; The Origins of Totalitarianism, The Human Condition; analyst of power and judgment", "conceptual, unsparing, civic-minded, provocatively clear"),
    "Federico Garcia Lorca": ("Spanish poet and playwright; Blood Wedding, Gypsy Ballads; icon of the Generation of '27", "moonlit, tragic, folkloric, blood-red"),
    "Italo Calvino": ("Italian novelist and essayist; Invisible Cities, If on a winter's night a traveler; master of combinatorial fiction", "weightless, geometric, playful, crystalline"),
    "Wu Jianren": ("Chinese novelist and journalist; Strange Events Eyewitnessed over Twenty Years; late-Qing social satirist", "episodic, caustic, panoramic, reform-minded"),
    "Feng Menglong": ("Chinese writer and editor; the Three Words story collections; preserver of vernacular Ming narrative", "earthy, anecdotal, worldly, proverb-rich"),
    "Lao She": ("Chinese novelist and playwright; Rickshaw Boy, Teahouse; chronicler of Beijing vernacular life", "vernacular, humane, tragicomic, streetwise"),
    "Eileen Chang": ("Chinese-American novelist and essayist; Love in a Fallen City, The Golden Cangue; anatomist of urban intimacy", "jewel-cut, sardonic, sensuous, emotionally cool"),
    "Ryunosuke Akutagawa": ("Japanese short-story writer; Rashomon, In a Grove; modern reworker of classical tales", "razor-edged, uncanny, erudite, morally unstable"),
    "Osamu Dazai": ("Japanese novelist; No Longer Human, The Setting Sun; confessional voice of alienation", "self-lacerating, decadent, intimate, darkly comic"),
    "George Washington": ("First U.S. president and Revolutionary War commander; established key precedents for the presidency", "grave, republican, restrained, duty-bound"),
    "John Adams": ("Second U.S. president, diplomat, and political theorist; advocate of independence and constitutional government", "learned, combative, candid, republican-austere"),
    "Thomas Jefferson": ("Third U.S. president and principal author of the Declaration of Independence; founder of the University of Virginia", "Enlightenment-inflected, elegant, agrarian, paradoxical"),
    "James Madison": ("Fourth U.S. president; principal architect of the Constitution and Bill of Rights", "constitutional, compressed, analytical, faction-aware"),
    "James Monroe": ("Fifth U.S. president and diplomat; associated with the Monroe Doctrine and Era of Good Feelings", "formal, steady, nationalizing, diplomatically guarded"),
    "John Quincy Adams": ("Sixth U.S. president, diplomat, and antislavery congressman; major early American foreign-policy strategist", "erudite, austere, principled, densely reasoned"),
    "Andrew Jackson": ("Seventh U.S. president and military commander; transformed mass-party politics amid coercive Indigenous removal", "pugnacious, populist, personal, command-heavy"),
    "Martin Van Buren": ("Eighth U.S. president and party organizer; key architect of the modern Democratic Party", "tactical, lawyerly, partisan, smoothly evasive"),
    "John Tyler": ("Tenth U.S. president; established presidential succession practice and supported Texas annexation", "states-rights minded, formal, defensive, constitutionalist"),
    "James K. Polk": ("Eleventh U.S. president; oversaw major territorial expansion and the Mexican-American War", "goal-driven, meticulous, expansionist, administratively spare"),
    "Zachary Taylor": ("Twelfth U.S. president and Mexican-American War general; brief presidency amid sectional crisis", "soldierly, terse, plain, unvarnished"),
    "Millard Fillmore": ("Thirteenth U.S. president; signed the Compromise of 1850, including the Fugitive Slave Act", "cautious, conciliatory, legalistic, order-seeking"),
    "Franklin Pierce": ("Fourteenth U.S. president; administration deepened sectional conflict through the Kansas-Nebraska era", "ornamental, conciliatory, party-loyal, evasive"),
    "James Buchanan": ("Fifteenth U.S. president and diplomat; presided over the accelerating secession crisis", "legalistic, temporizing, formal, status-quo bound"),
    "Andrew Johnson": ("Seventeenth U.S. president; led early Reconstruction and became the first president impeached", "defiant, extemporaneous, personalistic, confrontational"),
    "Ulysses S. Grant": ("Eighteenth U.S. president and Union general; defended Reconstruction and federal civil-rights enforcement", "direct, laconic, soldierly, unembellished"),
    "Rutherford B. Hayes": ("Nineteenth U.S. president; civil-service reformer whose accession marked the end of Reconstruction", "moderate, procedural, reformist, sober"),
    "James A. Garfield": ("Twentieth U.S. president, congressman, and scholar; assassinated early in office", "learned, self-made, reform-minded, oratorically balanced"),
    "Chester A. Arthur": ("Twenty-first U.S. president; surprised allies by advancing federal civil-service reform", "polished, reserved, administrative, quietly reformist"),
    "Grover Cleveland": ("Twenty-second and twenty-fourth U.S. president; advocate of limited government and executive independence", "blunt, fiscally austere, veto-minded, moralizing"),
    "Benjamin Harrison": ("Twenty-third U.S. president; oversaw antitrust legislation and expansion of federal activity", "precise, lawyerly, chilly, policy-dense"),
    "William McKinley": ("Twenty-fifth U.S. president; led the nation through the Spanish-American War and industrial expansion", "calm, protective, prosperity-minded, carefully managed"),
    "William Howard Taft": ("Twenty-seventh U.S. president and later chief justice; trust-buster and constitutional jurist", "judicial, genial, meticulous, institution-first"),
    "Woodrow Wilson": ("Twenty-eighth U.S. president and political scientist; wartime leader and advocate of the League of Nations", "professorial, moralizing, elevated, covenant-driven"),
    "Warren G. Harding": ("Twenty-ninth U.S. president and newspaper publisher; promoted a postwar return to normalcy", "soothing, alliterative, vague, boosterish"),
    "Calvin Coolidge": ("Thirtieth U.S. president; symbol of small-government conservatism during the 1920s", "laconic, dry, restrained, civic-moral"),
    "Herbert Hoover": ("Thirty-first U.S. president, engineer, and humanitarian; led during the onset of the Great Depression", "technical, voluntarist, managerial, emotionally distant"),
    "Harry S. Truman": ("Thirty-third U.S. president; ended World War II and shaped the early Cold War order", "plainspoken, decisive, homespun, combative"),
    "Dwight D. Eisenhower": ("Thirty-fourth U.S. president and Allied commander; managed Cold War containment and interstate-highway expansion", "measured, military-calm, consensus-minded, cautionary"),
    "Lyndon B. Johnson": ("Thirty-sixth U.S. president; enacted Great Society and landmark civil-rights legislation amid the Vietnam War", "forceful, legislative, moral-urgent, arm-twisting"),
    "Richard Nixon": ("Thirty-seventh U.S. president; opened relations with China and resigned over Watergate", "strategic, defensive, geopolitical, resentfully intimate"),
    "Gerald Ford": ("Thirty-eighth U.S. president; restored procedural stability after Watergate and pardoned Richard Nixon", "plain, healing, unpretentious, institution-steadying"),
    "Jimmy Carter": ("Thirty-ninth U.S. president and humanitarian; brokered the Camp David Accords and later won the Nobel Peace Prize", "earnest, moral, technocratic, confessional"),
    "Ronald Reagan": ("Fortieth U.S. president and former actor; conservative movement leader and late-Cold War communicator", "optimistic, anecdotal, cinematic, ideologically clear"),
    "George H. W. Bush": ("Forty-first U.S. president and diplomat; managed the Cold War's end and Gulf War coalition", "prudent, diplomatic, patrician, self-effacing"),
    "Bill Clinton": ("Forty-second U.S. president; New Democrat associated with economic expansion and welfare reform", "empathetic, policy-fluent, improvisational, triangulating"),
    "George W. Bush": ("Forty-third U.S. president; led after the September 11 attacks and launched wars in Afghanistan and Iraq", "plainspoken, moral-binary, folksy, faith-inflected"),
    "Bill Gates": ("American software entrepreneur and philanthropist; Microsoft co-founder and global-health funder", "systems-minded, explanatory, data-forward, solutionist"),
    "Elon Musk": ("Technology entrepreneur associated with electric vehicles, commercial spaceflight, and social media", "provocative, compressed, techno-futurist, meme-literate"),
    "Steve Jobs": ("American technology executive; Apple co-founder who reshaped personal computing, music, and mobile design", "minimalist, visionary, product-theatrical, intuitive"),
    "Tony Blair": ("British prime minister and Labour modernizer; led New Labour and supported intervention in Iraq", "modernizing, fluent, centrist, morally assertive"),
    "Boris Johnson": ("British politician, writer, and former prime minister; led Brexit implementation and the early pandemic response", "bumptious, allusive, comic, improvisational"),
    "Keir Starmer": ("British Labour politician and former director of public prosecutions; prime minister after the 2024 election", "prosecutorial, disciplined, managerial, change-with-caution"),
    "Theresa May": ("British former prime minister and home secretary; led early Brexit negotiations", "dutiful, controlled, security-minded, stiffly earnest"),
    "David Cameron": ("British former prime minister; led coalition austerity government and called the Brexit referendum", "smooth, pragmatic, clubbable, modernization-minded"),
    "Gordon Brown": ("British former prime minister and chancellor; central figure in the response to the global financial crisis", "weighty, moral-serious, statistics-rich, Presbyterian"),
    "John Major": ("British former prime minister; negotiated the Maastricht era and advanced the Northern Ireland peace process", "understated, decent, pragmatic, cricket-field plain"),
    "Rishi Sunak": ("British former prime minister and chancellor; led during inflation and post-pandemic fiscal strain", "technocratic, brisk, metrics-led, managerial"),
    "Liz Truss": ("British former prime minister and foreign secretary; advocate of low-tax market liberalism", "ideological, emphatic, liberty-branded, brittle"),
    "Kamala Harris": ("American lawyer and politician; former vice president, senator, and California attorney general", "prosecutorial, upbeat, coalition-minded, rhythmic"),
    "Hillary Clinton": ("American diplomat and politician; former secretary of state, senator, and presidential nominee", "policy-dense, resilient, disciplined, incrementalist"),
    "Bernie Sanders": ("American senator and democratic socialist; national advocate for universal healthcare and economic redistribution", "repetitive, class-focused, indignant, movement-driven"),
    "Elizabeth Warren": ("American senator and legal scholar; consumer-protection architect and critic of concentrated finance", "plan-heavy, pedagogical, prosecutorial, populist-progressive"),
    "Alexandria Ocasio-Cortez": ("American congresswoman and democratic socialist; prominent advocate of the Green New Deal", "digital-native, insurgent, vivid, movement-savvy"),
    "Ron DeSantis": ("American politician and Florida governor; conservative culture-war and executive-power advocate", "combative, disciplined, grievance-coded, prosecutorial"),
    "Justin Trudeau": ("Canadian politician and former prime minister; advanced progressive social policy and climate pricing", "inclusive, polished, bilingual, values-forward"),
    "Jacinda Ardern": ("New Zealand former prime minister; known for crisis communication and wellbeing-oriented governance", "empathetic, calm, communal, quietly resolute"),
    "Anthony Albanese": ("Australian prime minister and Labor politician; longtime advocate of working-class social democracy", "plainspoken, collegial, union-rooted, incremental"),
    "Adolf Hitler": ("German dictator and Nazi leader; responsible for World War II in Europe and the Holocaust", "demagogic, apocalyptic, conspiratorial, violently absolutist"),
    "Olaf Scholz": ("German politician and former chancellor; led the coalition response to Russia's invasion of Ukraine", "terse, lawyerly, cautious, technocratic"),
    "Charles de Gaulle": ("French general, statesman, and founder of the Fifth Republic; leader of Free France", "monumental, sovereignist, austere, historically grand"),
    "Francois Mitterrand": ("French president and Socialist statesman; advanced European integration and major domestic reforms", "literary, enigmatic, republican, ceremonially controlled"),
    "Pope Benedict XVI": ("German theologian and pope; author of major works on Christian doctrine and faith", "scholastic, contemplative, precise, tradition-conscious"),
    "Pope John Paul II": ("Polish pope and philosopher; global Catholic leader influential in opposition to communist rule", "pilgrimage-minded, philosophical, exhortative, human-dignity centered"),
    "Fidel Castro": ("Cuban revolutionary and longtime leader; central figure in Cold War socialism and one-party rule", "marathon, anti-imperialist, didactic, improvisational"),
    "Salvador Allende": ("Chilean socialist president; pursued democratic structural reform before the 1973 military coup", "solemn, constitutional, class-conscious, valedictory"),
    "Hugo Chavez": ("Venezuelan president and military officer; founder of Bolivarian socialist rule", "folksy, theatrical, confrontational, plebiscitary"),
    # 2026-07 expansion batch
    "Agatha Christie": ("English detective novelist; Hercule Poirot and early mysteries; best-selling novelist of all time", "plotted, brisk, tidy, misdirecting"),
    "G. K. Chesterton": ("English essayist and novelist; Father Brown stories, Orthodoxy; master of paradox", "paradoxical, jovial, aphoristic, combative"),
    "Rudyard Kipling": ("English writer of empire and India; The Jungle Book, Kim; Nobel laureate", "rhythmic, vivid, imperial, ballad-like"),
    "Lord Dunsany": ("Anglo-Irish fantasist; The Gods of Pegana; founder of modern fantasy prose", "mythic, ornate, dreamlike, incantatory"),
    "E. Nesbit": ("English children's novelist; Five Children and It, The Railway Children", "playful, brisk, wry, matter-of-fact magical"),
    "William Morris": ("English designer, poet, and fantasy pioneer; News from Nowhere, The Well at the World's End", "archaic, ornamental, utopian, romance-inflected"),
    "P. G. Wodehouse": ("English comic novelist; Jeeves and Blandings; virtuoso of the comic sentence", "farcical, urbane, exuberant, simile-rich"),
    "Sinclair Lewis": ("American novelist; Main Street, Babbitt; first American Nobel laureate in literature", "satirical, documentary, colloquial, deflating"),
    "Bram Stoker": ("Irish novelist; Dracula; gothic horror in documentary form", "epistolary, gothic, suspenseful, atmospheric"),
    "Mahatma Gandhi": ("Indian independence leader; nonviolent resistance and swaraj; wrote extensively in English", "plain, moral, patient, disarming"),
    "Rabindranath Tagore": ("Bengali polymath and first Asian Nobel laureate; English lectures on nationalism and personality", "lyrical, contemplative, universalist, serene"),
    "Swami Vivekananda": ("Indian monk who introduced Vedanta to the West; 1893 Chicago address", "exhortative, fiery, spiritual, direct"),
    "Frederick Douglass": ("American abolitionist and orator; escaped slavery to become a leading public voice", "searing, cadenced, indicting, dignified"),
    "Booker T. Washington": ("American educator and orator; Up from Slavery, Atlanta Exposition address", "pragmatic, anecdotal, conciliatory, industrious"),
    "Robert G. Ingersoll": ("American lawyer and orator; the Great Agnostic of the Gilded Age lecture circuit", "eloquent, irreverent, humane, rolling"),
    "Emmeline Pankhurst": ("British suffragette leader; militant campaign for women's votes", "defiant, urgent, disciplined, rallying"),
    "Liu E": ("Late-Qing novelist; The Travels of Lao Can; social panorama of a collapsing dynasty", "itinerant, observational, elegiac, reformist"),
    "Li Boyuan": ("Late-Qing satirist; Officialdom Unmasked; exposé fiction of bureaucratic corruption", "episodic, sardonic, panoramic, muckraking"),
    "Zeng Pu": ("Late-Qing novelist; A Flower in a Sinful Sea; roman à clef of diplomatic society", "allusive, cosmopolitan, satirical, dense"),
    "Su Manshu": ("Poet-monk and novelist of the late Qing; The Lone Swan; romantic hybrid of classical and modern", "melancholic, lyrical, confessional, ornate"),
    "Zhu Ziqing": ("Modern Chinese essayist; Beiying (Retreating Figure); model of vernacular prose", "limpid, restrained, tender, precise"),
    "Yu Dafu": ("May Fourth fiction writer; Sinking; confessional modern vernacular fiction", "confessional, brooding, sensual, self-lacerating"),
    "Sun Yat-sen": ("Founding father of the Republic of China; Three Principles of the People lectures", "programmatic, exhortative, nation-building, didactic"),
    "Liang Qichao": ("Late-Qing reformer and essayist; New Citizen essays; father of modern Chinese journalism", "torrential, exhortative, neologistic, galvanizing"),
    "Cai Yuanpei": ("Educator and president of Peking University; aesthetic education advocate", "measured, liberal, scholarly, reform-minded"),
    "Mori Ogai": ("Meiji novelist, translator, and army surgeon; The Wild Geese, The Dancing Girl", "classical, restrained, analytic, austere"),
    "Higuchi Ichiyo": ("Meiji woman writer; Takekurabe; classical diction turned on modern Tokyo life", "flowing, classical, compassionate, compressed"),
    "Miyazawa Kenji": ("Poet and children's author of Tohoku; Night on the Galactic Railroad", "cosmic, innocent, mineral-bright, devotional"),
    "Okamoto Kido": ("Playwright and detective novelist; the Hanshichi mysteries of old Edo", "atmospheric, antiquarian, deft, anecdotal"),
    "Izumi Kyoka": ("Novelist of the uncanny; The Holy Man of Mount Koya; gothic romanticism in Japanese", "phantasmagoric, ornate, eerie, incantatory"),
    "Shimazaki Toson": ("Naturalist novelist and poet; The Broken Commandment, Before the Dawn", "confessional, historical, sober, accumulative"),
    "Arishima Takeo": ("Taisho novelist; A Certain Woman; humanist fiction of self and society", "psychological, earnest, expansive, conflicted"),
    "Kunikida Doppo": ("Meiji writer; Musashino; lyrical naturalism and the modern short story", "lyrical, plain, nature-attuned, wistful"),
    "Victor Hugo": ("French Romantic titan; Les Misérables, Notre-Dame de Paris; also a monumental political orator", "oceanic, antithetical, visionary, declamatory"),
    "Guy de Maupassant": ("French master of the short story; Boule de Suif, Bel-Ami", "economical, ironic, sensory, pitiless"),
    "Jules Verne": ("French father of science fiction; Twenty Thousand Leagues Under the Seas", "expository, adventurous, enumerative, wonder-driven"),
    "Honore de Balzac": ("French novelist of La Comédie humaine; encyclopedist of post-Napoleonic society", "torrential, detailed, worldly, typological"),
    "Stendhal": ("French novelist; The Red and the Black, The Charterhouse of Parma; psychological precision", "dry, swift, ironic, analytical"),
    "George Sand": ("French novelist and memoirist; Consuelo; rural and romantic fiction", "flowing, idealistic, pastoral, humane"),
    "Alexandre Dumas": ("French novelist of historical adventure; The Three Musketeers, Monte Cristo", "propulsive, dialogic, swashbuckling, generous"),
    "Anatole France": ("French novelist and critic; Penguin Island; Nobel laureate ironist", "urbane, skeptical, classical, mischievous"),
    "Alphonse Daudet": ("Provençal novelist; Letters from My Windmill, Tartarin", "sunlit, affectionate, comic, anecdotal"),
    "Maurice Leblanc": ("French creator of Arsène Lupin, gentleman burglar", "playful, twisting, elegant, cliffhanging"),
    "Gaston Leroux": ("French mystery novelist; The Mystery of the Yellow Room, The Phantom of the Opera", "melodramatic, ingenious, journalistic, feverish"),
    "Emile Gaboriau": ("French pioneer of the detective novel; Monsieur Lecoq", "procedural, methodical, serialized, suspenseful"),
    "Theodor Fontane": ("German realist; Effi Briest; ironic chronicler of Prussian society", "conversational, ironic, poised, socially acute"),
    "Stefan Zweig": ("Austrian novelist and biographer; Amok, chess and passion novellas", "feverish, psychological, polished, propulsive"),
    "Rainer Maria Rilke": ("Prague-born German poet; The Notebooks of Malte Laurids Brigge", "inward, imagistic, elegiac, luminous"),
    "Heinrich Heine": ("German poet and essayist; Book of Songs, the Harz Journey", "witty, lyrical, barbed, self-ironizing"),
    "E. T. A. Hoffmann": ("German Romantic fantasist; The Golden Pot, tales of the uncanny", "grotesque, musical, uncanny, doubled"),
    "Arthur Schnitzler": ("Viennese playwright and novelist; Reigen, Casanova's Homecoming; anatomist of desire", "clinical, erotic, interior, disenchanted"),
    "Hermann Hesse": ("German-Swiss novelist; Siddhartha, Demian; Nobel laureate of the inward path", "meditative, seeking, parabolic, serene"),
    "Theodor Storm": ("North German novella master; Immensee, Der Schimmelreiter", "elegiac, coastal, framed, quietly tragic"),
    "Benito Perez Galdos": ("Spanish realist; Fortunata y Jacinta, the National Episodes", "panoramic, colloquial, humane, historical"),
    "Miguel de Unamuno": ("Basque philosopher-novelist; Mist, The Tragic Sense of Life", "agonistic, paradoxical, metaphysical, insistent"),
    "Vicente Blasco Ibanez": ("Valencian novelist; The Four Horsemen of the Apocalypse", "vigorous, regional, cinematic, polemical"),
    "Emilia Pardo Bazan": ("Galician countess and naturalist novelist; The House of Ulloa", "naturalist, incisive, descriptive, proto-feminist"),
    "Leopoldo Alas": ("Spanish novelist and critic 'Clarín'; La Regenta", "ironic, minute, provincial-panoramic, mordant"),
    "Pio Baroja": ("Basque novelist of the Generation of '98; The Quest trilogy", "abrupt, restless, unadorned, picaresque"),
    "Juan Valera": ("Spanish diplomat-novelist; Pepita Jiménez", "urbane, epistolary, classical, gently ironic"),
    "Luigi Pirandello": ("Sicilian dramatist and novelist; Six Characters in Search of an Author; Nobel laureate", "meta-theatrical, paradoxical, humoristic, destabilizing"),
    "Giovanni Verga": ("Sicilian verismo master; I Malavoglia", "choral, fatalistic, dialect-inflected, austere"),
    "Italo Svevo": ("Triestine modernist; Zeno's Conscience; comic psychoanalytic self-portraiture", "self-deprecating, analytic, digressive, wry"),
    "Edmondo De Amicis": ("Italian writer and traveler; Cuore, travel sketches of Europe and Morocco", "sentimental, observant, civic, descriptive"),
    "Antonio Fogazzaro": ("Italian novelist of faith and doubt; Piccolo mondo antico", "spiritual, romantic, alpine, conflicted"),
    "Ivan Turgenev": ("Russian novelist; Fathers and Sons; lyrical realism between generations", "lyrical, poised, elegiac, socially attuned"),
    "Nikolai Gogol": ("Russian-Ukrainian comic genius; Dead Souls, The Overcoat", "grotesque, digressive, fantastical, satirical"),
    "Alexander Pushkin": ("Russia's national poet; The Captain's Daughter; founder of modern Russian prose", "limpid, swift, ironic, classical"),
    "Ivan Goncharov": ("Russian novelist; Oblomov; the epic of inertia", "leisurely, ironic, domestic, accumulative"),
    "Nikolai Leskov": ("Russian storyteller; The Enchanted Wanderer, Lefty; skaz oral narration", "yarning, idiomatic, folkloric, sly"),
    "Alexander Kuprin": ("Russian realist; The Duel, The Garnet Bracelet", "sensuous, compassionate, soldierly, romantic"),
    "Maxim Gorky": ("Russian writer of the lower depths; Childhood; bridge to Soviet letters", "raw, vagabond, indignant, vitalist"),
    "Henryk Sienkiewicz": ("Polish national novelist; Quo Vadis, the Trilogy; Nobel laureate", "epic, patriotic, vivid, sweeping"),
    "Boleslaw Prus": ("Polish realist; The Doll, Pharaoh; chronicler of Warsaw", "analytical, humane, urban, quietly ironic"),
    "Wladyslaw Reymont": ("Polish novelist; The Peasants; Nobel laureate of the village year", "earthy, seasonal, choral, sensory"),
    "Stefan Zeromski": ("Polish novelist of conscience; Homeless People, The Coming Spring", "impassioned, wounded, civic, lyrical"),
    "Eliza Orzeszkowa": ("Polish positivist novelist; On the Niemen", "earnest, pastoral, reformist, detailed"),
}

with path.open(newline="", encoding="utf-8") as f:
    rows = list(csv.DictReader(f))
display_fields = ["photo_url", "profile", "style_traits"]
fields = [field for field in rows[0] if field not in display_fields] + display_fields
missing = sorted({row["name"] for row in rows} - profiles.keys())
if missing:
    raise ValueError(f"Missing person-specific metadata: {missing}")
with path.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        profile, traits = profiles[row["name"]]
        row.update(photo_url="", profile=profile, style_traits=traits)
        writer.writerow(row)
